# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(602, 574)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 601, 571))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("GIF/giphy.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 470, 151, 41))
        self.pushButton.setStyleSheet("background:Transparent;\n"
"border:4px solid blue;\n"
"border-radius:20px;\n"
"color:blue;\n"
"font-size:25px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 520, 151, 41))
        self.pushButton_2.setStyleSheet("background:Transparent;\n"
"border:4px solid red;\n"
"border-radius:20px;\n"
"color:red;\n"
"font-size:25px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.Textime = QtWidgets.QTextBrowser(Form)
        self.Textime.setGeometry(QtCore.QRect(230, 260, 181, 41))
        self.Textime.setStyleSheet("background:Transparent;\n"
"border:1px solid black;\n"
"color:white;\n"
"font-size:25px;\n"
"\n"
"")
        self.Textime.setObjectName("Textime")
        self.Textemp = QtWidgets.QTextBrowser(Form)
        self.Textemp.setGeometry(QtCore.QRect(0, 10, 81, 41))
        self.Textemp.setStyleSheet("background:Transparent;\n"
"border:1px solid black;\n"
"color:white;\n"
"font-size:20px;\n"
"text-align:center;\n"
"\n"
"")
        self.Textemp.setObjectName("Textemp")
        self.Textdate = QtWidgets.QTextBrowser(Form)
        self.Textdate.setGeometry(QtCore.QRect(390, 10, 211, 41))
        self.Textdate.setStyleSheet("background:Transparent;\n"
"border:1px solid black;\n"
"color:white;\n"
"font-size:20px;\n"
"text-align:center;\n"
"")
        self.Textdate.setObjectName("Textdate")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "START"))
        self.pushButton_2.setText(_translate("Form", "EXIT"))
# import rec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
